name: Run AsteraBot

on:
  workflow_dispatch:  # allows manual run from GitHub UI
  schedule:
    - cron: '0 */6 * * *'  # runs every 6 hours, adjust as needed

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests mwparserfromhell

      - name: Run bot
        env:
          BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
          BOT_PASSWORD: ${{ secrets.BOT_PASSWORD }}
        run: python bot.py
