name: Run AsteraBot TESTWIKI BIT

on:
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11  # or 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests mwparserfromhell

      - name: Run bot
        env:
          BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
          BOT_PASSWORD: ${{ secrets.BOT_PASSWORD }}
        run: |
          python bot.py

